//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 09:30:37 AM CST 
//


package com.maucc.xml.accounts;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.maucc.xml.accounts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.maucc.xml.accounts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordList }
     * 
     */
    public RecordList createRecordList() {
        return new RecordList();
    }

    /**
     * Create an instance of {@link RecordList.EachRecord }
     * 
     */
    public RecordList.EachRecord createRecordListEachRecord() {
        return new RecordList.EachRecord();
    }

    /**
     * Create an instance of {@link RecordList.EachRecord.AddressList }
     * 
     */
    public RecordList.EachRecord.AddressList createRecordListEachRecordAddressList() {
        return new RecordList.EachRecord.AddressList();
    }

    /**
     * Create an instance of {@link RecordList.EachRecord.AddressList.Address }
     * 
     */
    public RecordList.EachRecord.AddressList.Address createRecordListEachRecordAddressListAddress() {
        return new RecordList.EachRecord.AddressList.Address();
    }

    /**
     * Create an instance of {@link RecordList.EachRecord.AddressList.Address.TabLabel }
     * 
     */
    public RecordList.EachRecord.AddressList.Address.TabLabel createRecordListEachRecordAddressListAddressTabLabel() {
        return new RecordList.EachRecord.AddressList.Address.TabLabel();
    }

}
