//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 11:56:22 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:soap.bigmachines.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.maucc.xml.accounts;
