//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 09:30:37 AM CST 
//


package com.maucc.xml.accounts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.persistence.oxm.annotations.XmlCDATA;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="site_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="each_record" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="customer_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="customer_rep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="address_list">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="address">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="tab_label">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="fr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="zh_CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="zh_TW" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="de" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ja_JP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="pt_PT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ru_RU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ko_KR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="it" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="fr_CA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="pt_BR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="billing_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="separate_ship_addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shipping_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="attribute_list" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siteVersion",
    "eachRecord"
})
@XmlRootElement(name = "record_list")
public class RecordList {

    @XmlElement(name = "site_version", required = true)
    @XmlCDATA
    protected String siteVersion;
    @XmlElement(name = "each_record")
    protected List<RecordList.EachRecord> eachRecord;

    /**
     * Gets the value of the siteVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteVersion() {
        return siteVersion;
    }

    /**
     * Sets the value of the siteVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteVersion(String value) {
        this.siteVersion = value;
    }

    /**
     * Gets the value of the eachRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eachRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEachRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecordList.EachRecord }
     * 
     * 
     */
    public List<RecordList.EachRecord> getEachRecord() {
        if (eachRecord == null) {
            eachRecord = new ArrayList<RecordList.EachRecord>();
        }
        return this.eachRecord;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="customer_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="customer_rep" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="address_list">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="address">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="tab_label">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="fr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="zh_CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="zh_TW" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="de" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ja_JP" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="pt_PT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ru_RU" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="ko_KR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="it" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="fr_CA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="pt_BR" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="billing_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="separate_ship_addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="billing_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shipping_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="attribute_list" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "category",
        "action",
        "firstName",
        "lastName",
        "customerId",
        "companyName",
        "customerRep",
        "phone",
        "email",
        "fax",
        "addressList",
        "attributeList"
    })
    public static class EachRecord {

        @XmlElement(required = true)
        protected String category;
        @XmlElement(required = true)
        protected String action;
        @XmlElement(name = "first_name", required = true)
        protected String firstName;
        @XmlElement(name = "last_name", required = true)
        protected String lastName;
        @XmlElement(name = "customer_id", required = true)
        protected String customerId;
        @XmlElement(name = "company_name", required = true)
        protected String companyName;
        @XmlElement(name = "customer_rep", required = true)
        protected String customerRep;
        @XmlElement(required = true)
        protected String phone;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(required = true)
        protected String fax;
        @XmlElement(name = "address_list", required = true)
        protected RecordList.EachRecord.AddressList addressList;
        @XmlElement(name = "attribute_list", required = true)
        protected String attributeList;

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the customerId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerId() {
            return customerId;
        }

        /**
         * Sets the value of the customerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerId(String value) {
            this.customerId = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyName(String value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the customerRep property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerRep() {
            return customerRep;
        }

        /**
         * Sets the value of the customerRep property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerRep(String value) {
            this.customerRep = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhone() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhone(String value) {
            this.phone = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the fax property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFax() {
            return fax;
        }

        /**
         * Sets the value of the fax property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFax(String value) {
            this.fax = value;
        }

        /**
         * Gets the value of the addressList property.
         * 
         * @return
         *     possible object is
         *     {@link RecordList.EachRecord.AddressList }
         *     
         */
        public RecordList.EachRecord.AddressList getAddressList() {
            return addressList;
        }

        /**
         * Sets the value of the addressList property.
         * 
         * @param value
         *     allowed object is
         *     {@link RecordList.EachRecord.AddressList }
         *     
         */
        public void setAddressList(RecordList.EachRecord.AddressList value) {
            this.addressList = value;
        }

        /**
         * Gets the value of the attributeList property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttributeList() {
            return attributeList;
        }

        /**
         * Sets the value of the attributeList property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttributeList(String value) {
            this.attributeList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="address">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="tab_label">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="fr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="zh_CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="zh_TW" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="de" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ja_JP" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="pt_PT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ru_RU" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="ko_KR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="it" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="fr_CA" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="pt_BR" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="billing_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="separate_ship_addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="billing_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shipping_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address"
        })
        public static class AddressList {

            @XmlElement(required = true)
            protected RecordList.EachRecord.AddressList.Address address;

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link RecordList.EachRecord.AddressList.Address }
             *     
             */
            public RecordList.EachRecord.AddressList.Address getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link RecordList.EachRecord.AddressList.Address }
             *     
             */
            public void setAddress(RecordList.EachRecord.AddressList.Address value) {
                this.address = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="tab_label">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="fr" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="zh_CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="zh_TW" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="de" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ja_JP" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="pt_PT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ru_RU" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="ko_KR" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="it" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="fr_CA" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="pt_BR" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="billing_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_company" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_company_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_address" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_address_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="separate_ship_addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="billing_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shipping_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tabLabel",
                "billingFirstName",
                "billingLastName",
                "billingCompany",
                "billingCompany2",
                "billingAddress",
                "billingAddress2",
                "billingCity",
                "billingState",
                "billingZip",
                "billingCountry",
                "billingPhone",
                "billingFax",
                "billingEmail",
                "shippingFirstName",
                "shippingLastName",
                "shippingCompany",
                "shippingCompany2",
                "shippingAddress",
                "shippingAddress2",
                "shippingCity",
                "shippingState",
                "shippingZip",
                "shippingCountry",
                "shippingPhone",
                "shippingFax",
                "shippingEmail",
                "separateShipAddr",
                "billingId",
                "shippingId"
            })
            public static class Address {

                @XmlElement(name = "tab_label", required = true)
                protected RecordList.EachRecord.AddressList.Address.TabLabel tabLabel;
                @XmlElement(name = "billing_first_name", required = true)
                protected String billingFirstName;
                @XmlElement(name = "billing_last_name", required = true)
                protected String billingLastName;
                @XmlElement(name = "billing_company", required = true)
                protected String billingCompany;
                @XmlElement(name = "billing_company_2", required = true)
                protected String billingCompany2;
                @XmlElement(name = "billing_address", required = true)
                protected String billingAddress;
                @XmlElement(name = "billing_address_2", required = true)
                protected String billingAddress2;
                @XmlElement(name = "billing_city", required = true)
                protected String billingCity;
                @XmlElement(name = "billing_state", required = true)
                protected String billingState;
                @XmlElement(name = "billing_zip", required = true)
                protected String billingZip;
                @XmlElement(name = "billing_country", required = true)
                protected String billingCountry;
                @XmlElement(name = "billing_phone", required = true)
                protected String billingPhone;
                @XmlElement(name = "billing_fax", required = true)
                protected String billingFax;
                @XmlElement(name = "billing_email", required = true)
                protected String billingEmail;
                @XmlElement(name = "shipping_first_name", required = true)
                protected String shippingFirstName;
                @XmlElement(name = "shipping_last_name", required = true)
                protected String shippingLastName;
                @XmlElement(name = "shipping_company", required = true)
                protected String shippingCompany;
                @XmlElement(name = "shipping_company_2", required = true)
                protected String shippingCompany2;
                @XmlElement(name = "shipping_address", required = true)
                protected String shippingAddress;
                @XmlElement(name = "shipping_address_2", required = true)
                protected String shippingAddress2;
                @XmlElement(name = "shipping_city", required = true)
                protected String shippingCity;
                @XmlElement(name = "shipping_state", required = true)
                protected String shippingState;
                @XmlElement(name = "shipping_zip", required = true)
                protected String shippingZip;
                @XmlElement(name = "shipping_country", required = true)
                protected String shippingCountry;
                @XmlElement(name = "shipping_phone", required = true)
                protected String shippingPhone;
                @XmlElement(name = "shipping_fax", required = true)
                protected String shippingFax;
                @XmlElement(name = "shipping_email", required = true)
                protected String shippingEmail;
                @XmlElement(name = "separate_ship_addr", required = true)
                protected String separateShipAddr;
                @XmlElement(name = "billing_id", required = true)
                protected String billingId;
                @XmlElement(name = "shipping_id", required = true)
                protected String shippingId;

                /**
                 * Gets the value of the tabLabel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RecordList.EachRecord.AddressList.Address.TabLabel }
                 *     
                 */
                public RecordList.EachRecord.AddressList.Address.TabLabel getTabLabel() {
                    return tabLabel;
                }

                /**
                 * Sets the value of the tabLabel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RecordList.EachRecord.AddressList.Address.TabLabel }
                 *     
                 */
                public void setTabLabel(RecordList.EachRecord.AddressList.Address.TabLabel value) {
                    this.tabLabel = value;
                }

                /**
                 * Gets the value of the billingFirstName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingFirstName() {
                    return billingFirstName;
                }

                /**
                 * Sets the value of the billingFirstName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingFirstName(String value) {
                    this.billingFirstName = value;
                }

                /**
                 * Gets the value of the billingLastName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingLastName() {
                    return billingLastName;
                }

                /**
                 * Sets the value of the billingLastName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingLastName(String value) {
                    this.billingLastName = value;
                }

                /**
                 * Gets the value of the billingCompany property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingCompany() {
                    return billingCompany;
                }

                /**
                 * Sets the value of the billingCompany property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingCompany(String value) {
                    this.billingCompany = value;
                }

                /**
                 * Gets the value of the billingCompany2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingCompany2() {
                    return billingCompany2;
                }

                /**
                 * Sets the value of the billingCompany2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingCompany2(String value) {
                    this.billingCompany2 = value;
                }

                /**
                 * Gets the value of the billingAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingAddress() {
                    return billingAddress;
                }

                /**
                 * Sets the value of the billingAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingAddress(String value) {
                    this.billingAddress = value;
                }

                /**
                 * Gets the value of the billingAddress2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingAddress2() {
                    return billingAddress2;
                }

                /**
                 * Sets the value of the billingAddress2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingAddress2(String value) {
                    this.billingAddress2 = value;
                }

                /**
                 * Gets the value of the billingCity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingCity() {
                    return billingCity;
                }

                /**
                 * Sets the value of the billingCity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingCity(String value) {
                    this.billingCity = value;
                }

                /**
                 * Gets the value of the billingState property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingState() {
                    return billingState;
                }

                /**
                 * Sets the value of the billingState property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingState(String value) {
                    this.billingState = value;
                }

                /**
                 * Gets the value of the billingZip property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingZip() {
                    return billingZip;
                }

                /**
                 * Sets the value of the billingZip property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingZip(String value) {
                    this.billingZip = value;
                }

                /**
                 * Gets the value of the billingCountry property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingCountry() {
                    return billingCountry;
                }

                /**
                 * Sets the value of the billingCountry property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingCountry(String value) {
                    this.billingCountry = value;
                }

                /**
                 * Gets the value of the billingPhone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingPhone() {
                    return billingPhone;
                }

                /**
                 * Sets the value of the billingPhone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingPhone(String value) {
                    this.billingPhone = value;
                }

                /**
                 * Gets the value of the billingFax property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingFax() {
                    return billingFax;
                }

                /**
                 * Sets the value of the billingFax property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingFax(String value) {
                    this.billingFax = value;
                }

                /**
                 * Gets the value of the billingEmail property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingEmail() {
                    return billingEmail;
                }

                /**
                 * Sets the value of the billingEmail property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingEmail(String value) {
                    this.billingEmail = value;
                }

                /**
                 * Gets the value of the shippingFirstName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingFirstName() {
                    return shippingFirstName;
                }

                /**
                 * Sets the value of the shippingFirstName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingFirstName(String value) {
                    this.shippingFirstName = value;
                }

                /**
                 * Gets the value of the shippingLastName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingLastName() {
                    return shippingLastName;
                }

                /**
                 * Sets the value of the shippingLastName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingLastName(String value) {
                    this.shippingLastName = value;
                }

                /**
                 * Gets the value of the shippingCompany property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingCompany() {
                    return shippingCompany;
                }

                /**
                 * Sets the value of the shippingCompany property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingCompany(String value) {
                    this.shippingCompany = value;
                }

                /**
                 * Gets the value of the shippingCompany2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingCompany2() {
                    return shippingCompany2;
                }

                /**
                 * Sets the value of the shippingCompany2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingCompany2(String value) {
                    this.shippingCompany2 = value;
                }

                /**
                 * Gets the value of the shippingAddress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingAddress() {
                    return shippingAddress;
                }

                /**
                 * Sets the value of the shippingAddress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingAddress(String value) {
                    this.shippingAddress = value;
                }

                /**
                 * Gets the value of the shippingAddress2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingAddress2() {
                    return shippingAddress2;
                }

                /**
                 * Sets the value of the shippingAddress2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingAddress2(String value) {
                    this.shippingAddress2 = value;
                }

                /**
                 * Gets the value of the shippingCity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingCity() {
                    return shippingCity;
                }

                /**
                 * Sets the value of the shippingCity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingCity(String value) {
                    this.shippingCity = value;
                }

                /**
                 * Gets the value of the shippingState property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingState() {
                    return shippingState;
                }

                /**
                 * Sets the value of the shippingState property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingState(String value) {
                    this.shippingState = value;
                }

                /**
                 * Gets the value of the shippingZip property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingZip() {
                    return shippingZip;
                }

                /**
                 * Sets the value of the shippingZip property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingZip(String value) {
                    this.shippingZip = value;
                }

                /**
                 * Gets the value of the shippingCountry property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingCountry() {
                    return shippingCountry;
                }

                /**
                 * Sets the value of the shippingCountry property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingCountry(String value) {
                    this.shippingCountry = value;
                }

                /**
                 * Gets the value of the shippingPhone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingPhone() {
                    return shippingPhone;
                }

                /**
                 * Sets the value of the shippingPhone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingPhone(String value) {
                    this.shippingPhone = value;
                }

                /**
                 * Gets the value of the shippingFax property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingFax() {
                    return shippingFax;
                }

                /**
                 * Sets the value of the shippingFax property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingFax(String value) {
                    this.shippingFax = value;
                }

                /**
                 * Gets the value of the shippingEmail property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingEmail() {
                    return shippingEmail;
                }

                /**
                 * Sets the value of the shippingEmail property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingEmail(String value) {
                    this.shippingEmail = value;
                }

                /**
                 * Gets the value of the separateShipAddr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSeparateShipAddr() {
                    return separateShipAddr;
                }

                /**
                 * Sets the value of the separateShipAddr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSeparateShipAddr(String value) {
                    this.separateShipAddr = value;
                }

                /**
                 * Gets the value of the billingId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBillingId() {
                    return billingId;
                }

                /**
                 * Sets the value of the billingId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBillingId(String value) {
                    this.billingId = value;
                }

                /**
                 * Gets the value of the shippingId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingId() {
                    return shippingId;
                }

                /**
                 * Sets the value of the shippingId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingId(String value) {
                    this.shippingId = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="en" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="fr" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="zh_CN" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="zh_TW" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="de" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="es" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ja_JP" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="pt_PT" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ru_RU" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="ko_KR" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="it" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="fr_CA" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="pt_BR" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "en",
                    "fr",
                    "zhCN",
                    "zhTW",
                    "de",
                    "es",
                    "jaJP",
                    "ptPT",
                    "ruRU",
                    "koKR",
                    "it",
                    "frCA",
                    "ptBR"
                })
                public static class TabLabel {

                    @XmlElement(required = true)
                    protected String en;
                    @XmlElement(required = true)
                    protected String fr;
                    @XmlElement(name = "zh_CN", required = true)
                    protected String zhCN;
                    @XmlElement(name = "zh_TW", required = true)
                    protected String zhTW;
                    @XmlElement(required = true)
                    protected String de;
                    @XmlElement(required = true)
                    protected String es;
                    @XmlElement(name = "ja_JP", required = true)
                    protected String jaJP;
                    @XmlElement(name = "pt_PT", required = true)
                    protected String ptPT;
                    @XmlElement(name = "ru_RU", required = true)
                    protected String ruRU;
                    @XmlElement(name = "ko_KR", required = true)
                    protected String koKR;
                    @XmlElement(required = true)
                    protected String it;
                    @XmlElement(name = "fr_CA", required = true)
                    protected String frCA;
                    @XmlElement(name = "pt_BR", required = true)
                    protected String ptBR;

                    /**
                     * Gets the value of the en property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEn() {
                        return en;
                    }

                    /**
                     * Sets the value of the en property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEn(String value) {
                        this.en = value;
                    }

                    /**
                     * Gets the value of the fr property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFr() {
                        return fr;
                    }

                    /**
                     * Sets the value of the fr property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFr(String value) {
                        this.fr = value;
                    }

                    /**
                     * Gets the value of the zhCN property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getZhCN() {
                        return zhCN;
                    }

                    /**
                     * Sets the value of the zhCN property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setZhCN(String value) {
                        this.zhCN = value;
                    }

                    /**
                     * Gets the value of the zhTW property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getZhTW() {
                        return zhTW;
                    }

                    /**
                     * Sets the value of the zhTW property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setZhTW(String value) {
                        this.zhTW = value;
                    }

                    /**
                     * Gets the value of the de property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDe() {
                        return de;
                    }

                    /**
                     * Sets the value of the de property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDe(String value) {
                        this.de = value;
                    }

                    /**
                     * Gets the value of the es property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEs() {
                        return es;
                    }

                    /**
                     * Sets the value of the es property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEs(String value) {
                        this.es = value;
                    }

                    /**
                     * Gets the value of the jaJP property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getJaJP() {
                        return jaJP;
                    }

                    /**
                     * Sets the value of the jaJP property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setJaJP(String value) {
                        this.jaJP = value;
                    }

                    /**
                     * Gets the value of the ptPT property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPtPT() {
                        return ptPT;
                    }

                    /**
                     * Sets the value of the ptPT property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPtPT(String value) {
                        this.ptPT = value;
                    }

                    /**
                     * Gets the value of the ruRU property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRuRU() {
                        return ruRU;
                    }

                    /**
                     * Sets the value of the ruRU property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRuRU(String value) {
                        this.ruRU = value;
                    }

                    /**
                     * Gets the value of the koKR property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getKoKR() {
                        return koKR;
                    }

                    /**
                     * Sets the value of the koKR property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setKoKR(String value) {
                        this.koKR = value;
                    }

                    /**
                     * Gets the value of the it property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIt() {
                        return it;
                    }

                    /**
                     * Sets the value of the it property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIt(String value) {
                        this.it = value;
                    }

                    /**
                     * Gets the value of the frCA property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFrCA() {
                        return frCA;
                    }

                    /**
                     * Sets the value of the frCA property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFrCA(String value) {
                        this.frCA = value;
                    }

                    /**
                     * Gets the value of the ptBR property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPtBR() {
                        return ptBR;
                    }

                    /**
                     * Sets the value of the ptBR property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPtBR(String value) {
                        this.ptBR = value;
                    }

                }

            }

        }

    }

}
