//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 01:46:57 PM CST 
//


package com.maucc.xml.transcations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.maucc.xml.transcations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.maucc.xml.transcations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateTransactionResponse }
     * 
     */
    public CreateTransactionResponse createCreateTransactionResponse() {
        return new CreateTransactionResponse();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction }
     * 
     */
    public CreateTransactionResponse.Transaction createCreateTransactionResponseTransaction() {
        return new CreateTransactionResponse.Transaction();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml createCreateTransactionResponseTransactionDataXml() {
        return new CreateTransactionResponse.Transaction.DataXml();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess createCreateTransactionResponseTransactionDataXmlQuoteProcess() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleData() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Status }
     * 
     */
    public CreateTransactionResponse.Status createCreateTransactionResponseStatus() {
        return new CreateTransactionResponse.Status();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.ActionData }
     * 
     */
    public CreateTransactionResponse.Transaction.ActionData createCreateTransactionResponseTransactionActionData() {
        return new CreateTransactionResponse.Transaction.ActionData();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.ObsoleteAttributes }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.ObsoleteAttributes createCreateTransactionResponseTransactionDataXmlQuoteProcessObsoleteAttributes() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.ObsoleteAttributes();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.BottomLineDiscountPercentQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.BottomLineDiscountPercentQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataBottomLineDiscountPercentQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.BottomLineDiscountPercentQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContracSection62GeneralLOLQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContracSection62GeneralLOLQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContracSection62GeneralLOLQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContracSection62GeneralLOLQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.TaxesQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.TaxesQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataTaxesQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.TaxesQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6ServicesTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6ServicesTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup6ServicesTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6ServicesTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4HardwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4HardwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup4HardwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4HardwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.GoodDealQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.GoodDealQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGoodDealQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.GoodDealQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4TotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4TotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup4TotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4TotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractDirectionsHTMLQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractDirectionsHTMLQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractDirectionsHTMLQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractDirectionsHTMLQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection4TerminationQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection4TerminationQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection4TerminationQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection4TerminationQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5HardwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5HardwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup5HardwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5HardwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion5Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion5Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoCodesPromotion5Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion5Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5ServicesTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5ServicesTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup5ServicesTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5ServicesTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion3Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion3Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoCodesPromotion3Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion3Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PreviousDealDataQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PreviousDealDataQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPreviousDealDataQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PreviousDealDataQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailFreeShippingQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailFreeShippingQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoDetailFreeShippingQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailFreeShippingQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion3Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion3Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoDetailPromotion3Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion3Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection5DisclaimerOfWarrantiesHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection5DisclaimerOfWarrantiesHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection5DisclaimerOfWarrantiesHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection5DisclaimerOfWarrantiesHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.EndUsersQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.EndUsersQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataEndUsersQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.EndUsersQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ConfidentialInformationQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ConfidentialInformationQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataConfidentialInformationQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ConfidentialInformationQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2TotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2TotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup2TotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2TotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion1Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion1Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoCodesPromotion1Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion1Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4ServicesTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4ServicesTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup4ServicesTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4ServicesTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion4Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion4Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoCodesPromotion4Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion4Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceScheduleQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceScheduleQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataServiceScheduleQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceScheduleQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PreviousDealsQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PreviousDealsQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPreviousDealsQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PreviousDealsQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection1ServicesHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection1ServicesHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection1ServicesHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection1ServicesHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3SoftwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3SoftwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup3SoftwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3SoftwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6SoftwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6SoftwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup6SoftwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6SoftwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection8ConfidentialityQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection8ConfidentialityQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection8ConfidentialityQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection8ConfidentialityQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection31WhenDueBCDQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection31WhenDueBCDQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection31WhenDueBCDQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection31WhenDueBCDQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5SoftwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5SoftwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup5SoftwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5SoftwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.EndUserDataQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.EndUserDataQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataEndUserDataQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.EndUserDataQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.MaximumTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.MaximumTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataMaximumTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.MaximumTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6HardwareTotal }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6HardwareTotal createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup6HardwareTotal() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6HardwareTotal();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.SowSection1HeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.SowSection1HeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataSowSection1HeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.SowSection1HeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6TotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6TotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup6TotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group6TotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection7IndemnificationHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection7IndemnificationHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection7IndemnificationHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection7IndemnificationHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3HardwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3HardwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup3HardwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3HardwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2SoftwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2SoftwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup2SoftwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2SoftwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.SLAAttachmentQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.SLAAttachmentQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataSLAAttachmentQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.SLAAttachmentQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.FairDealQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.FairDealQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataFairDealQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.FairDealQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection3PaymentHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection3PaymentHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection3PaymentHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection3PaymentHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.CommissionLostQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.CommissionLostQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataCommissionLostQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.CommissionLostQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection2TermHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection2TermHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection2TermHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection2TermHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromotionalDiscounts }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromotionalDiscounts createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromotionalDiscounts() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromotionalDiscounts();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion2Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion2Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoDetailPromotion2Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion2Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4SoftwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4SoftwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup4SoftwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group4SoftwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection1Services }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection1Services createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection1Services() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection1Services();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataServiceQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2ServicesTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2ServicesTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup2ServicesTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2ServicesTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1TotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1TotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup1TotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1TotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.MinimumTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.MinimumTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataMinimumTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.MinimumTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.AdditionalContractNotesQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.AdditionalContractNotesQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataAdditionalContractNotesQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.AdditionalContractNotesQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion1Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion1Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoDetailPromotion1Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion1Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection20DefinitionsHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection20DefinitionsHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection20DefinitionsHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection20DefinitionsHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ExcellentDealQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ExcellentDealQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataExcellentDealQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ExcellentDealQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion2Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion2Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoCodesPromotion2Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesPromotion2Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5TotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5TotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup5TotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group5TotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1ServicesTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1ServicesTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup1ServicesTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1ServicesTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection4TerminationHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection4TerminationHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection4TerminationHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection4TerminationHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3TotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3TotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup3TotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3TotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection7IndemnificationQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection7IndemnificationQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection7IndemnificationQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection7IndemnificationQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection8ConfidentialityHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection8ConfidentialityHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection8ConfidentialityHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection8ConfidentialityHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion5Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion5Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoDetailPromotion5Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion5Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesFreeShippingQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesFreeShippingQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoCodesFreeShippingQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoCodesFreeShippingQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1HardwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1HardwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup1HardwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1HardwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PartUploadConfirmQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PartUploadConfirmQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPartUploadConfirmQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PartUploadConfirmQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2HardwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2HardwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup2HardwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group2HardwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection5DisclaimerOfWarrantiesQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection5DisclaimerOfWarrantiesQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection5DisclaimerOfWarrantiesQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection5DisclaimerOfWarrantiesQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.TechSolutionsServiceGuideQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.TechSolutionsServiceGuideQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataTechSolutionsServiceGuideQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.TechSolutionsServiceGuideQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection32DisputeQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection32DisputeQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection32DisputeQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection32DisputeQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection6LimitationOnLiabilityHeaderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection6LimitationOnLiabilityHeaderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection6LimitationOnLiabilityHeaderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection6LimitationOnLiabilityHeaderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection2TermQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection2TermQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection2TermQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection2TermQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion4Quote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion4Quote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataPromoDetailPromotion4Quote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.PromoDetailPromotion4Quote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection61WaiverConsequentialDamagesQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection61WaiverConsequentialDamagesQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataContractSection61WaiverConsequentialDamagesQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ContractSection61WaiverConsequentialDamagesQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceOrderQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceOrderQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataServiceOrderQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ServiceOrderQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.WhiteCoverPagePreviewQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.WhiteCoverPagePreviewQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataWhiteCoverPagePreviewQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.WhiteCoverPagePreviewQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ScontractSection63SubcapForCustomerDataQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ScontractSection63SubcapForCustomerDataQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataScontractSection63SubcapForCustomerDataQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.ScontractSection63SubcapForCustomerDataQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1SoftwareTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1SoftwareTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup1SoftwareTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group1SoftwareTotalQuote();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3ServicesTotalQuote }
     * 
     */
    public CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3ServicesTotalQuote createCreateTransactionResponseTransactionDataXmlQuoteProcessRuleDataGroup3ServicesTotalQuote() {
        return new CreateTransactionResponse.Transaction.DataXml.QuoteProcess.RuleData.Group3ServicesTotalQuote();
    }

}
