//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 02:57:28 PM CST 
//


package com.maucc.xml.datatables;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="records_read" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="records_failed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="records_inserted" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status"
})
@XmlRootElement(name = "addResponse")
public class AddResponse {

    @XmlElement(required = true)
    protected AddResponse.Status status;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AddResponse.Status }
     *     
     */
    public AddResponse.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddResponse.Status }
     *     
     */
    public void setStatus(AddResponse.Status value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="records_read" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="records_failed" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="records_inserted" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "success",
        "message",
        "recordsRead",
        "recordsFailed",
        "recordsInserted"
    })
    public static class Status {

        @XmlElement(required = true)
        protected String success;
        @XmlElement(required = true)
        protected String message;
        @XmlElement(name = "records_read")
        protected byte recordsRead;
        @XmlElement(name = "records_failed")
        protected byte recordsFailed;
        @XmlElement(name = "records_inserted")
        protected byte recordsInserted;

        /**
         * Gets the value of the success property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuccess() {
            return success;
        }

        /**
         * Sets the value of the success property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuccess(String value) {
            this.success = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

        /**
         * Gets the value of the recordsRead property.
         * 
         */
        public byte getRecordsRead() {
            return recordsRead;
        }

        /**
         * Sets the value of the recordsRead property.
         * 
         */
        public void setRecordsRead(byte value) {
            this.recordsRead = value;
        }

        /**
         * Gets the value of the recordsFailed property.
         * 
         */
        public byte getRecordsFailed() {
            return recordsFailed;
        }

        /**
         * Sets the value of the recordsFailed property.
         * 
         */
        public void setRecordsFailed(byte value) {
            this.recordsFailed = value;
        }

        /**
         * Gets the value of the recordsInserted property.
         * 
         */
        public byte getRecordsInserted() {
            return recordsInserted;
        }

        /**
         * Sets the value of the recordsInserted property.
         * 
         */
        public void setRecordsInserted(byte value) {
            this.recordsInserted = value;
        }

    }

}
